global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'wazuh'
    static_configs:
      - targets: ['wazuh:55000']

  # Add more monitoring targets as needed
